name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: make build
      - name: Push image
        run: echo $DOCKER_ACCESS_TOKEN | docker login -u jondpenton --password-stdin
