name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
            
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          # Username used to log against the Docker registry
          username: jondpenton # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
      
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          # Push is a shorthand for --output=type=registry
          push: true # optional, default is false
          # List of tags
          tags: jondpenton/gitpod-base:latest # optional
